<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="RDT039" name="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction" tests="50" failures="3" timestamp="25 Feb 2019 05:36:28 GMT" time="817.174" errors="3">
  <testcase name="TW_Dashboard_transactions" time="11.921" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="12.345" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="9.339" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="150.493" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction">
    <error type="org.openqa.selenium.TimeoutException" message="Timed out after 20 seconds waiting for presence of element located by: By.xpath: //android.view.View[@content-desc=&quot;Credit cards&quot;]
Build info: version: &#039;2.45.0&#039;, revision: &#039;5017cb8e7ca8e37638dc3091b2440b90a1d8686f&#039;, time: &#039;2015-02-27 09:10:26&#039;
System info: host: &#039;RDT039&#039;, ip: &#039;192.168.100.35&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_201&#039;
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.citibank.mobile.tw.sit, deviceScreenSize=1440x2560, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, deviceName=emulator-5554, platform=LINUX, deviceUDID=emulator-5554, appActivity=com.citi.mobile.pt3.GlobalPhoneActivity, androidInstallTimeout=150000, desired={appPackage=com.citibank.mobile.tw.sit, appActivity=com.citi.mobile.pt3.GlobalPhoneActivity, androidInstallTimeout=150000, platformVersion=8.1.0, skipUnlock=true, autoGrantPermissions=true, platformName=Android, deviceName=emulator-5554}, platformVersion=8.1.0, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, skipUnlock=true, autoGrantPermissions=true, javascriptEnabled=true, deviceModel=Android SDK built for x86, platformName=Android, deviceManufacturer=Google}]
Session ID: 11929958-fea3-4062-a950-d16a9fad8255">
      <![CDATA[org.openqa.selenium.TimeoutException: Timed out after 20 seconds waiting for presence of element located by: By.xpath: //android.view.View[@content-desc="Credit cards"]
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'RDT039', ip: '192.168.100.35', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.citibank.mobile.tw.sit, deviceScreenSize=1440x2560, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, deviceName=emulator-5554, platform=LINUX, deviceUDID=emulator-5554, appActivity=com.citi.mobile.pt3.GlobalPhoneActivity, androidInstallTimeout=150000, desired={appPackage=com.citibank.mobile.tw.sit, appActivity=com.citi.mobile.pt3.GlobalPhoneActivity, androidInstallTimeout=150000, platformVersion=8.1.0, skipUnlock=true, autoGrantPermissions=true, platformName=Android, deviceName=emulator-5554}, platformVersion=8.1.0, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, skipUnlock=true, autoGrantPermissions=true, javascriptEnabled=true, deviceModel=Android SDK built for x86, platformName=Android, deviceManufacturer=Google}]
Session ID: 11929958-fea3-4062-a950-d16a9fad8255
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:79)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
at com.citi.mobileAutomation.utils.ResuableFunction.getTextFromElementByWait(ResuableFunction.java:193)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:45)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:41)
at com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction.TW_Dashboard_transactions(Test_TW_Dashboard_Transaction.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.46 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'RDT039', ip: '192.168.100.35', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.citibank.mobile.tw.sit, deviceScreenSize=1440x2560, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, deviceName=emulator-5554, platform=LINUX, deviceUDID=emulator-5554, appActivity=com.citi.mobile.pt3.GlobalPhoneActivity, androidInstallTimeout=150000, desired={appPackage=com.citibank.mobile.tw.sit, appActivity=com.citi.mobile.pt3.GlobalPhoneActivity, androidInstallTimeout=150000, platformVersion=8.1.0, skipUnlock=true, autoGrantPermissions=true, platformName=Android, deviceName=emulator-5554}, platformVersion=8.1.0, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, skipUnlock=true, autoGrantPermissions=true, javascriptEnabled=true, deviceModel=Android SDK built for x86, platformName=Android, deviceManufacturer=Google}]
Session ID: 11929958-fea3-4062-a950-d16a9fad8255
*** Element info: {Using=xpath, value=//android.view.View[@content-desc="Credit cards"]}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:51)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:67)
at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:449)
at io.appium.java_client.DefaultGenericMobileDriver.findElementByXPath(DefaultGenericMobileDriver.java:145)
at io.appium.java_client.AppiumDriver.findElementByXPath(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.findElementByXPath(AndroidDriver.java:1)
at org.openqa.selenium.By$ByXPath.findElement(By.java:357)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:63)
at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:730)
at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:39)
at org.openqa.selenium.support.ui.ExpectedConditions$3.apply(ExpectedConditions.java:106)
at org.openqa.selenium.support.ui.ExpectedConditions$3.apply(ExpectedConditions.java:103)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
... 29 more
]]>
    </error>
  </testcase> <!-- TW_Dashboard_transactions -->
  <testcase name="TW_Dashboard_transactions" time="8.835" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="14.093" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="21.098" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="6.852" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="10.120" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="49.244" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="15.017" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="6.426" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:15)
at com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction.TW_Dashboard_transactions(Test_TW_Dashboard_Transaction.java:19)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TW_Dashboard_transactions -->
  <testcase name="TW_Dashboard_transactions" time="12.982" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="9.261" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="12.441" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="8.935" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="25.711" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="19.142" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="13.170" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="12.097" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="8.645" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="8.391" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="9.512" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="40.170" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:60)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:51)
at com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction.TW_Dashboard_transactions(Test_TW_Dashboard_Transaction.java:19)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TW_Dashboard_transactions -->
  <testcase name="TW_Dashboard_transactions" time="9.932" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="16.123" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="9.909" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="9.976" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="10.118" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:15)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:46)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:51)
at com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction.TW_Dashboard_transactions(Test_TW_Dashboard_Transaction.java:19)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TW_Dashboard_transactions -->
  <testcase name="TW_Dashboard_transactions" time="9.795" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="9.677" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="8.576" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="10.296" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="12.124" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="9.043" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.util.StringTokenizer.<init>(Unknown Source)
at java.util.StringTokenizer.<init>(Unknown Source)
at com.citi.mobileAutomation.dataMapping.KeyWords_Engine.splitBy(KeyWords_Engine.java:38)
at com.citi.mobileAutomation.dataMapping.KeyWords_Engine.returnValue(KeyWords_Engine.java:22)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:17)
at com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction.TW_Dashboard_transactions(Test_TW_Dashboard_Transaction.java:19)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TW_Dashboard_transactions -->
  <testcase name="TW_Dashboard_transactions" time="9.822" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="9.791" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="12.367" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="13.987" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="24.982" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="13.832" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="10.160" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="10.707" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="10.269" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="32.451" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="12.442" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="8.705" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="9.238" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
  <testcase name="TW_Dashboard_transactions" time="12.706" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:15)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:46)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:51)
at com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction.TW_Dashboard_transactions(Test_TW_Dashboard_Transaction.java:19)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TW_Dashboard_transactions -->
  <testcase name="TW_Dashboard_transactions" time="13.906" classname="com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction"/>
</testsuite> <!-- com.citi.mobileAutomation.test_TW_Dashboard.Test_TW_Dashboard_Transaction -->
