<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="apples-MacBook-Pro.local" name="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY" tests="34" failures="3" timestamp="18 Jul 2019 10:47:50 GMT" time="223.967" errors="0">
  <testcase name="gettingDashboard" time="3.788" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="2.185" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="9.606" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="1.963" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="1.891" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="1.953" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="2.116" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="1.855" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="1.986" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="4.282" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="1.417" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="2.450" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="1.989" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="1.558" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="8.204" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="54.139" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
	at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:103)
	at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:46)
	at com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY.gettingDashboard(Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- gettingDashboard -->
  <testcase name="gettingDashboard" time="27.210" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="2.714" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="40.918" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
	at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:103)
	at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:46)
	at com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY.gettingDashboard(Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY.java:25)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- gettingDashboard -->
  <testcase name="gettingDashboard" time="2.935" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="2.248" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="2.049" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="2.195" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
	at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:103)
	at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:46)
	at com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY.gettingDashboard(Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY.java:25)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- gettingDashboard -->
  <testcase name="gettingDashboard" time="1.905" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="6.594" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="2.390" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="1.626" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="10.757" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="1.979" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="0.949" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="0.211" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="4.400" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="1.470" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
  <testcase name="gettingDashboard" time="10.035" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY"/>
</testsuite> <!-- com.citi.mobileAutomation.test_SG.Test_Apac_iOS_Externalcc_Adhoc_LCY_LCY -->
