<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="apples-MacBook-Pro-4.local" name="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD" tests="28" failures="0" timestamp="14 May 2019 09:51:23 GMT" time="143.923" errors="3">
  <testcase name="gettingDataEPP" time="0.233" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="0.197" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:15)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:75)
at com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD.gettingDataEPP(Test__EMEA_PL_AD_140_TD.java:24)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="3.890" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="3.910" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="0.232" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:15)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:75)
at com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD.gettingDataEPP(Test__EMEA_PL_AD_140_TD.java:24)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="3.791" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="3.926" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="3.892" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="3.809" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="6.650" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="3.795" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="4.014" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="3.803" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="3.857" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="3.729" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="3.792" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="3.857" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="10.586" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="44.367" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="3.797" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="3.750" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="4.388" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="3.787" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="3.810" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="0.205" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:15)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:75)
at com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD.gettingDataEPP(Test__EMEA_PL_AD_140_TD.java:24)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="4.306" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="3.747" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
  <testcase name="gettingDataEPP" time="3.803" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD"/>
</testsuite> <!-- com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_140_TD -->
