<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="apples-MacBook-Pro-4.local" name="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings" tests="28" failures="4" timestamp="14 May 2019 08:51:43 GMT" time="398.403" errors="2">
  <testcase name="gettingDataEPP" time="0.279" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="35.217" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="6.438" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="13.197" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="33.700" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:68)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:75)
at com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings.gettingDataEPP(Test__EMEA_PL_AD_100_Savings.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="6.498" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="6.511" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="1.259" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="67.268" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:68)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:64)
at com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings.gettingDataEPP(Test__EMEA_PL_AD_100_Savings.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="22.449" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings">
    <error type="org.openqa.selenium.TimeoutException" message="Timed out after 20 seconds waiting for presence of element located by: By.xpath: (//XCUIElementTypeOther[@name=&quot;View_HeaderContainer&quot;]//XCUIElementTypeStaticText)[4]
Build info: version: &#039;2.45.0&#039;, revision: &#039;5017cb8e7ca8e37638dc3091b2440b90a1d8686f&#039;, time: &#039;2015-02-27 09:10:26&#039;
System info: host: &#039;apples-MacBook-Pro-4.local&#039;, ip: &#039;192.168.100.30&#039;, os.name: &#039;Mac OS X&#039;, os.arch: &#039;x86_64&#039;, os.version: &#039;10.14.4&#039;, java.version: &#039;1.8.0_211&#039;
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/apple/Downloads/PL_SIT2_7May_DEBUG.app, networkConnectionEnabled=false, bundleId=com.citi.development, databaseEnabled=false, deviceName=iPhone 8 Plus, platform=MAC, newCommandTimeout=3000, platformVersion=12.1, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=78EC92FC-390A-4085-8809-9EB94A7E9BF1, autoAcceptAlerts=true}]
Session ID: c50b9ca5-2730-4222-813b-d8d147ac16d4">
      <![CDATA[org.openqa.selenium.TimeoutException: Timed out after 20 seconds waiting for presence of element located by: By.xpath: (//XCUIElementTypeOther[@name="View_HeaderContainer"]//XCUIElementTypeStaticText)[4]
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'apples-MacBook-Pro-4.local', ip: '192.168.100.30', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.4', java.version: '1.8.0_211'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/apple/Downloads/PL_SIT2_7May_DEBUG.app, networkConnectionEnabled=false, bundleId=com.citi.development, databaseEnabled=false, deviceName=iPhone 8 Plus, platform=MAC, newCommandTimeout=3000, platformVersion=12.1, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=78EC92FC-390A-4085-8809-9EB94A7E9BF1, autoAcceptAlerts=true}]
Session ID: c50b9ca5-2730-4222-813b-d8d147ac16d4
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:79)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
at com.citi.mobileAutomation.utils.ResuableFunction.getTextFromElementByWait(ResuableFunction.java:183)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:39)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:75)
at com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings.gettingDataEPP(Test__EMEA_PL_AD_100_Savings.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5.08 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'apples-MacBook-Pro-4.local', ip: '192.168.100.30', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.4', java.version: '1.8.0_211'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/apple/Downloads/PL_SIT2_7May_DEBUG.app, networkConnectionEnabled=false, bundleId=com.citi.development, databaseEnabled=false, deviceName=iPhone 8 Plus, platform=MAC, newCommandTimeout=3000, platformVersion=12.1, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=78EC92FC-390A-4085-8809-9EB94A7E9BF1, autoAcceptAlerts=true}]
Session ID: c50b9ca5-2730-4222-813b-d8d147ac16d4
*** Element info: {Using=xpath, value=(//XCUIElementTypeOther[@name="View_HeaderContainer"]//XCUIElementTypeStaticText)[4]}
at sun.reflect.GeneratedConstructorAccessor25.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:51)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:67)
at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.findElement(IOSDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:449)
at io.appium.java_client.DefaultGenericMobileDriver.findElementByXPath(DefaultGenericMobileDriver.java:145)
at io.appium.java_client.AppiumDriver.findElementByXPath(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.findElementByXPath(IOSDriver.java:1)
at org.openqa.selenium.By$ByXPath.findElement(By.java:357)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:63)
at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.findElement(IOSDriver.java:1)
at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:730)
at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:39)
at org.openqa.selenium.support.ui.ExpectedConditions$3.apply(ExpectedConditions.java:106)
at org.openqa.selenium.support.ui.ExpectedConditions$3.apply(ExpectedConditions.java:103)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
... 29 more
]]>
    </error>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="20.645" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="45.189" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="19.510" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="1.208" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="0.984" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="6.475" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="6.605" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="0.903" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="1.113" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="33.448" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:68)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:75)
at com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings.gettingDataEPP(Test__EMEA_PL_AD_100_Savings.java:24)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="6.463" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="22.596" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings">
    <error type="org.openqa.selenium.TimeoutException" message="Timed out after 20 seconds waiting for presence of element located by: By.xpath: (//XCUIElementTypeOther[@name=&quot;View_HeaderContainer&quot;]//XCUIElementTypeStaticText)[4]
Build info: version: &#039;2.45.0&#039;, revision: &#039;5017cb8e7ca8e37638dc3091b2440b90a1d8686f&#039;, time: &#039;2015-02-27 09:10:26&#039;
System info: host: &#039;apples-MacBook-Pro-4.local&#039;, ip: &#039;192.168.100.30&#039;, os.name: &#039;Mac OS X&#039;, os.arch: &#039;x86_64&#039;, os.version: &#039;10.14.4&#039;, java.version: &#039;1.8.0_211&#039;
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/apple/Downloads/PL_SIT2_7May_DEBUG.app, networkConnectionEnabled=false, bundleId=com.citi.development, databaseEnabled=false, deviceName=iPhone 8 Plus, platform=MAC, newCommandTimeout=3000, platformVersion=12.1, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=78EC92FC-390A-4085-8809-9EB94A7E9BF1, autoAcceptAlerts=true}]
Session ID: c50b9ca5-2730-4222-813b-d8d147ac16d4">
      <![CDATA[org.openqa.selenium.TimeoutException: Timed out after 20 seconds waiting for presence of element located by: By.xpath: (//XCUIElementTypeOther[@name="View_HeaderContainer"]//XCUIElementTypeStaticText)[4]
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'apples-MacBook-Pro-4.local', ip: '192.168.100.30', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.4', java.version: '1.8.0_211'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/apple/Downloads/PL_SIT2_7May_DEBUG.app, networkConnectionEnabled=false, bundleId=com.citi.development, databaseEnabled=false, deviceName=iPhone 8 Plus, platform=MAC, newCommandTimeout=3000, platformVersion=12.1, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=78EC92FC-390A-4085-8809-9EB94A7E9BF1, autoAcceptAlerts=true}]
Session ID: c50b9ca5-2730-4222-813b-d8d147ac16d4
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:79)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
at com.citi.mobileAutomation.utils.ResuableFunction.getTextFromElementByWait(ResuableFunction.java:183)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:39)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:75)
at com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings.gettingDataEPP(Test__EMEA_PL_AD_100_Savings.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5.29 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'apples-MacBook-Pro-4.local', ip: '192.168.100.30', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.4', java.version: '1.8.0_211'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/apple/Downloads/PL_SIT2_7May_DEBUG.app, networkConnectionEnabled=false, bundleId=com.citi.development, databaseEnabled=false, deviceName=iPhone 8 Plus, platform=MAC, newCommandTimeout=3000, platformVersion=12.1, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=78EC92FC-390A-4085-8809-9EB94A7E9BF1, autoAcceptAlerts=true}]
Session ID: c50b9ca5-2730-4222-813b-d8d147ac16d4
*** Element info: {Using=xpath, value=(//XCUIElementTypeOther[@name="View_HeaderContainer"]//XCUIElementTypeStaticText)[4]}
at sun.reflect.GeneratedConstructorAccessor25.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:51)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:67)
at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.findElement(IOSDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:449)
at io.appium.java_client.DefaultGenericMobileDriver.findElementByXPath(DefaultGenericMobileDriver.java:145)
at io.appium.java_client.AppiumDriver.findElementByXPath(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.findElementByXPath(IOSDriver.java:1)
at org.openqa.selenium.By$ByXPath.findElement(By.java:357)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:63)
at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.findElement(IOSDriver.java:1)
at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:730)
at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:39)
at org.openqa.selenium.support.ui.ExpectedConditions$3.apply(ExpectedConditions.java:106)
at org.openqa.selenium.support.ui.ExpectedConditions$3.apply(ExpectedConditions.java:103)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
... 29 more
]]>
    </error>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="6.477" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="6.669" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="6.630" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="6.689" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="7.574" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="6.409" classname="com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings">
    <failure type="java.lang.AssertionError" message="expected [On deposit] but found [Make a transfer]">
      <![CDATA[java.lang.AssertionError: expected [On deposit] but found [Make a transfer]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:9)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:40)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:75)
at com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings.gettingDataEPP(Test__EMEA_PL_AD_100_Savings.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
</testsuite> <!-- com.citi.mobileAutomation.test_PL_iOS.Test__EMEA_PL_AD_100_Savings -->
