<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="apples-MacBook-Pro.local" name="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY" tests="31" failures="5" timestamp="17 Jul 2019 14:22:43 GMT" time="282.764" errors="0">
  <testcase name="gettingDashboard" time="2.011" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="1.567" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="10.264" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="4.727" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="3.109" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="2.271" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="2.526" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="2.203" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="9.112" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="27.226" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="2.942" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="4.232" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="2.095" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="4.531" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="15.256" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="2.658" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="2.749" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
	at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:103)
	at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:46)
	at com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY.gettingDashboard(Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY.java:25)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- gettingDashboard -->
  <testcase name="gettingDashboard" time="45.731" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
	at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:107)
	at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:46)
	at com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY.gettingDashboard(Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY.java:25)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- gettingDashboard -->
  <testcase name="gettingDashboard" time="0.358" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="45.925" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
	at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:103)
	at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:46)
	at com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY.gettingDashboard(Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY.java:25)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- gettingDashboard -->
  <testcase name="gettingDashboard" time="10.940" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="2.031" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:15)
	at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:50)
	at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:46)
	at com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY.gettingDashboard(Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- gettingDashboard -->
  <testcase name="gettingDashboard" time="0.247" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="2.546" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="2.005" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="2.517" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="9.486" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="10.698" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="2.336" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="2.066" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY"/>
  <testcase name="gettingDashboard" time="46.399" classname="com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
	at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:103)
	at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:46)
	at com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY.gettingDashboard(Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY.java:25)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- gettingDashboard -->
</testsuite> <!-- com.citi.mobileAutomation.test_SG.Test_Apac_iOS_FP_Internal_Adhoc_FCY_LCY -->
